# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterpise_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[('basic', 'BASIC'), ('premium', 'PREMIUM'), ('rich', 'RICH')], max_length=40, null=True)),
            ],
        ),
    ]
