# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0002_auto_20181018_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterpise_data',
            old_name='cat',
            new_name='cats',
        ),
        migrations.RenameField(
            model_name='enterpise_data',
            old_name='table',
            new_name='tables',
        ),
    ]
