# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0003_auto_20181018_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpise_data',
            name='tables',
            field=models.CharField(choices=[('enterpirse_data.venues_basic', 'BASIC'), ('enterpirse_data.venues_premium', 'PREMIUM'), ('enterpirse_data.venues_rich', 'RICH')], default='BASIC', max_length=40),
        ),
    ]
